[phases.setup]
nixpkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app" 